# Generated by Django 4.2.14 on 2024-07-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_protect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('aadhaar', models.CharField(max_length=12, unique=True)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('document_path', models.CharField(max_length=255)),
                ('doct_file_name', models.CharField(max_length=255)),
            ],
        ),
    ]
