# Generated by Django 4.2.14 on 2024-08-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_protect', '0003_remove_employee_email_employee_cdr_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='cdr_files',
        ),
        migrations.AddField(
            model_name='employee',
            name='cdr_files_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='cdr_files_path',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
