# Generated by Django 4.2.14 on 2024-08-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_protect', '0004_remove_employee_cdr_files_employee_cdr_files_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cdr_files_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cdr_files_path',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
